---
- name: make installation folder
  file:
    path: ~/q3mm
    state: directory

- name: upload q3mm instance
  unarchive:
    copy: yes
    dest: ~/q3mm/
    src: ../q3mm_instance/target/universal/q3mm_instance-1.0-SNAPSHOT.zip

- stat: path=~/Steam/steamcmd
  register: steam_cmd

- stat: path=~/Steam/steamcmd/steamapps/common/qlds
  register: qlserver  

- name: make steamcmd dir
  when: steam_cmd.stat.exists == False
  file:
    path: ~/Steam/
    state: directory

- name: install steamcmd deps
  apt:
    name: lib32gcc1
    state: latest

- name: get steamcmd
  when: steam_cmd.stat.exists == False
  shell: curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
  args:
    chdir: ~/Steam

- name: install qlserver
  when: qlserver.stat.exists == False
  shell: ./steamcmd.sh +login anonymous +force_install_dir ./steamapps/common/qlds/ +app_update 349090 +quit 
  args:
    chdir: ~/Steam

- name: qlserver deps
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libczmq-dev
    - lib32z1
    - g++
    - libstdc++6:i386

- name: copy maplist
  copy:
    src: ../q3mm_instance/src/main/resources/duel.txt
    dest: ~/Steam/steamapps/common/qlds/duel.txt
    
