---
- name: make installation folder
  file:
    name: ~/q3mm
    diretory: yes
    

- name: install q3mm front
  copy:
    src: ../target/universal/q3mm-1.0-SNAPSHOT.zip
    dest: ~/q3mm/q3mm-1.0-SNAPSHOT.zip

- name: unzip
  shell: unzip /home/dehun/q3mm/q3mm-1.0-SNAPSHOT.zip
  
